### ISSUE TITLE
How do we store the database of image data?

### ISSUE THREAD

**Issue by major** [redhatcloudx/rhelocator#47]
Now that we can retrieve data from the big cloud providers and work is underway on a common schema, we need to think about how we plan to store that information so the rhelocator can access it.

Since the container has all of the data within it and a new container must be deployed to update the data, it seems like storing the database in memory would make sense. That should help with performance. However, I'm not sure how much data we would be storing in memory. Hopefully not much.

What ideas so do we have here?

**Comment by FKolwa** [comment]
Hm. It might be worth considering if we really need to store the entire Json db in memory at all times.
The default way of loading Json data is rather inefficient as keys are stored in different sized memory chunks based on their data type ranging from 1 to 4 bytes per character (this doesn't sound like much but it can easily quadruple the size of your Json file in memory). 

We could however consider solutions like [lru_cache](https://docs.python.org/3/library/functools.html#functools.lru_cache)  to cache often repeated DB operations in memory.

**Comment by major** [comment]
Agreed on the `lru_cache`. That could be a handy way to cache individual methods and such. SQLite makes sense to me since writing is nowhere near a priority for us. [TinyDB](https://github.com/msiemens/tinydb) could also be an option. Redis could work, but then we might need a service container along with our main container.

**Comment by FKolwa** [comment]
The team has decided to move our image data storage to a Postgres JSON store. Follow up implementation tasks will be created.
