### ISSUE TITLE
Extend amount of images returned from Azure

### ISSUE THREAD

**Issue by FKolwa** [redhatcloudx/rhelocator#50]
Currently the amount of images returned from Azure are a bit restrictive.
This is the entire list:

> [
  {
    "offer": "RHEL",
    "publisher": "redhat",
    "sku": "7lvm-gen2",
    "urn": "redhat:RHEL:7lvm-gen2:7.9.2022032206",
    "version": "7.9.2022032206"
  },
  {
    "offer": "RHEL",
    "publisher": "redhat",
    "sku": "8-lvm-gen2",
    "urn": "redhat:RHEL:8-lvm-gen2:8.6.2022051814",
    "version": "8.6.2022051814"
  },
  {
    "offer": "RHEL",
    "publisher": "redhat",
    "sku": "9-lvm-gen2",
    "urn": "redhat:RHEL:9-lvm-gen2:9.0.2022090601",
    "version": "9.0.2022090601"
  }
]

We should revisit which images should be available in the image locator and what image information are necessary. 

Parameters missing from the image information:
- "hyperVGeneration"

**Comment by yuxisun1217** [comment]
Hi @FKolwa ,

Usually I used the azure-cli to get all the RHEL images:
```az vm image list --all --publisher RedHat --offer RHEL```
With this command I can get 700+ images.

For the Microsoft built images, the image with "gen2" in the sku are generation 2 images. Others are gen1.
For Stratosphere images it is opposite: the images with "gen1" in the sku are generation 1 images. Others are gen2.

Besides, with azure-cli we can also get the architecture info, which I think is also important for the filter:
```
  {
    "architecture": "x64",
    "offer": "RHEL",
    "publisher": "RedHat",
    "sku": "7-LVM",
    "urn": "RedHat:RHEL:7-LVM:latest",
    "urnAlias": "RHEL",
    "version": "latest"
  }
```

Hope it can help. Thanks!

**Comment by FKolwa** [comment]
Oh wow, thanks for the heads-up with the gen1 / gen2 images that is really helpful advice.
Yeah there is a ton of images on Azure.
We're currently trying to figure out which of the available images we want to display to customers. If you have further inside in that issue (image types / builds that are commonly used .. ) we would highly appreciate it!

**Comment by yuxisun1217** [comment]
Hi @FKolwa ,
Here is the Microsoft document that shows the RHEL image types:
https://learn.microsoft.com/en-us/azure/virtual-machines/workloads/redhat/redhat-images
There're some dimensions, like generation(1/2), PAYG/BYOS, arch...

Here is a detail list: (But it seem some information in this list are not correct. Now all the new images use cloud-init as provisioning agent, not Linux Agent. And the partitions of all the new images are LVM.).
https://learn.microsoft.com/en-us/azure/virtual-machines/workloads/redhat/redhat-imagelist

The gold images are with "rhel-byos" offer:
https://learn.microsoft.com/en-us/azure/virtual-machines/workloads/redhat/byos

Not quite sure if it can help :)

**Comment by yuxisun1217** [comment]
IMO generally all the PAYG images(the image types in the https://learn.microsoft.com/en-us/azure/virtual-machines/workloads/redhat/redhat-images except the rhel-byos offers) can be shown. For BYOS images, only the customers that register to the Red Hat cloud access can use them, maybe we can hide this part, or allow the customer to filter out the PAYG or BYOS images?
